name: cleanup-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * 0'
      # At 6 AM every Sunday

jobs:
  coronation:
    runs-on: thevickypedia-lite
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
