name: none-shall-pass

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*.md'
      - '!jarvis/**'
      - '!docs/**'
      - '!docs_gen/**'

jobs:
  none-shall-pass:
    runs-on: thevickypedia-lite
    steps:
      - uses: actions/checkout@v4
      - uses: thevickypedia/none-shall-pass@v5
